rhinofi/client-js

- examples/05.submitOrder.js
- examples/08.cancelOrder.js
- examples/10.getOrder.js
- examples/17.ledgerDeposit.js
- examples/18.ledgerSubmitOrder.js
- examples/helpers/examplesList.js
- examples/src/cancelOrder.js
- examples/src/getOrder.js
- examples/src/ledgerDeposit.js
- examples/src/ledgerSubmitOrder.js
- examples/src/submitOrder.js
fixes #17 
- Updated examples for submitOrder, getOrder and cancelOrder to align with new submitOrder method.
- Added ledgerSubmitOrder Example.
> Update examples - fixes #17

- src/api/ledger/deposit.test.js
- src/api/ledger/withdraw.test.js
- src/api/submitOrder.test.js
- src/config.js
- src/lib/dvf/bindApi.js
- src/lib/dvf/computeBuySellDats.js
- src/lib/dvf/generateRandomNonce.js
- src/lib/ledger/selectTransport.js
- src/lib/stark/ledger/createSignedOrder.js
- src/lib/stark/ledger/createSignedTransfer.js
- src/lib/stark/ledger/getBits.js
- src/lib/stark/ledger/getPath.js
- src/lib/stark/ledger/getPublicKey.js
- src/lib/stark/ledger/getPublicKey.test.js
Using path derivation logic agreed by Ledger, StarkWare and Deversifi to create a unique path for Stark public keys based on the Ethereum path.
> Deriving Unique Ledger Stark Path for every Eth Path 

- package.json
- src/api/ledger/deposit.test.js
- src/api/ledger/withdraw.test.js
- src/api/submitOrder.test.js
- src/lib/stark/ledger/getPublicKey.test.js
- yarn.lock
Test cases with mock ledger calls.
> Enhanced Test Cases for Ledger

- src/api/contract/abi/StarkEx.abi.js
- src/api/getConfig.test.js
- src/api/getUserConfig.test.js
- src/api/test/fixtures/getConf.js
- src/lib/stark/ledger/getPublicKey.js
Remove leading zeroes so that the front end never has the public key with leading zeroes.
> ensuring public key alwasy has leading zeroes removed

- src/api/deposit.js
Adding txHash to deposit response so that front end can query tx status and block depth if required.
> adding txHash to deposit response

- src/api/contract/depositCancel.js
- src/api/contract/depositReclaim.js
- src/api/contract/fullWithdrawalRequest.js
- src/dvf.js
- src/lib/dvf/bindApi.js
Functions such as depositCancel, depositReclaim are useful to the user in the case where something goes wrong with their on-chain deposit (such as making it to the wrong vault).
> Implements additional contract functions

- src/api/get30DaysVolume.js
- src/api/get30DaysVolume.test.js
- src/api/getFeeRate.test.js
- src/lib/dvf/bindApi.js
- src/lib/dvf/get-authenticated.js
- Authenticated feeRate end point.
- Authenticated 30 days trading volume
- Enhanced test cases
> Authenticated feeRate and 30DaysVolume methods

- examples/01.register.js
- examples/02.deposit.js
- examples/03.getDeposits.js
- examples/04.getBalance.js
- examples/05.submitOrder.js
- examples/06.getOrders.js
- examples/07.getOrders_forSymbolPair.js
- examples/08.cancelOrder.js
- examples/09.getConfig.js
- examples/10.getOrder.js
- examples/11.getOrdersHist.js
- examples/12.getUserConfig.js
- examples/13.withdraw.js
- examples/14.getWithdrawals.js
- examples/15.getWithdrawal.js
- examples/16.getVaultId.js
- examples/17.ledgerDeposit.js
- examples/18.ledgerSubmitOrder.js
- examples/helpers/example.js.tmpl
- examples/src/deposit.js
Updated pub api endpoint to point to staging environment for all examples
> Use Staging Env for Examples

- examples/02.deposit.js
- examples/05.submitOrder.js
- examples/08.cancelOrder.js
- examples/10.getOrder.js
- examples/19.ledgerDeposit.js
- examples/20.ledgerSubmitOrder.js
- examples/21.ledgerWithdraw.js
- examples/helpers/examplesList.js
- examples/src/cancelOrder.js
- examples/src/deposit.js
- examples/src/getOrder.js
- examples/src/getOrders_forSymbolPair.js
- examples/src/ledgerDeposit.js
- examples/src/ledgerSubmitOrder.js
- examples/src/ledgerWithdraw.js
- examples/src/submitOrder.js
- Updated getOrder and cancelOrder examples to use _id to retrieve orderId
- update getOrders for a symbol based to retrieve orders for a symbol
- Added withdraw example for ledger
> Order tweaks and ledger additions

- src/dvf.js
Catching error while getting network id.
> When getting chain id catch error

- src/api/submitMarketOrder.test.js
- src/lib/stark/createMarketOrder.js
- update tests to validate that the buy and sell amounts are correct as they will be expected by backend
- reverse worst case price when necessary
> Fix market order creation

- package.json
- src/api/contract/deposit.js
- src/api/deposit.js
- src/api/withdraw.js
ETH amounts need to be in multiples of quantization else contract deposit will cause an error.
> Validate and adjust amount to 8 decimal places

- package.json
- src/api/getConfig.test.js
- src/api/getUserConfig.test.js
- src/api/submitMarketOrder.js
- src/api/submitMarketOrder.test.js
- src/api/submitOrder.js
- src/api/submitOrder.test.js
- src/api/test/fixtures/getConf.js
- src/lib/dvf/createMarketOrderMetaData.js
- src/lib/dvf/createMarketOrderPayload.js
- src/lib/dvf/createOrderMetaData.js
- src/lib/dvf/createOrderPayload.js
- src/lib/stark/createMarketOrder.js
- src/lib/stark/createOrder.js
- yarn.lock
Reverts DeversiFi/dvf-client-js#60
> Revert "Incorporate Settle Spread Where applicable"

- package.json
> Bumping up dvf client version

- README.md
( ./src/lib/error/reasons.js#L1 )= 404 
updated to - 
(./src/lib/dvf/errorReasons.js#L1)
> 📝update README.md

- README.md
- src/api/getConfig.test.js
- src/config.js
- Increase nonce validity to 12 hours
> Increase nonce age to 12 hours

- examples/05.submitOrder.js
- examples/helpers/getPriceFromOrderBook.js
- src/api/estimatedNextBatchTime.js
- src/api/estimatedNextBatchTime.test.js
- src/api/register.js
- src/api/submitMarketOrder.js
- src/api/submitOrder.js
- src/lib/bfx/getTickers.js
- src/lib/dvf/bindApi.js
- src/lib/dvf/createMarketOrderPayload.js
- src/lib/dvf/createOrderPayload.js
- Optimised reading of on-chain available withdrawal balances
- Hidden and post only orders
- wallet type parameter in register
> Dev => Master

- examples/00.setup.js
- examples/01.register.js
- examples/02.deposit.js
- examples/03.getDeposits.js
- examples/04.getBalance.js
- examples/05.submitOrder.js
- examples/06.getOrders.js
- examples/07.getOrders_forSymbolPair.js
- examples/08.cancelOrder.js
- examples/09.getConfig.js
- examples/10.getOrder.js
- examples/11.getOrdersHist.js
- examples/12.getUserConfig.js
- examples/13.withdraw.js
- examples/14.getWithdrawals.js
- examples/15.getWithdrawal.js
- examples/16.withdrawOnChain.js
- examples/17.fullWithdrawalRequest.js
- examples/18.getVaultId.js
- examples/19.ledgerDeposit.js
- examples/20.ledgerSubmitOrder.js
- examples/21.ledgerWithdraw.js
- examples/22.cancelWithdrawal.js
- examples/helpers/buildExamples.js
- examples/helpers/example.js.tmpl
- examples/helpers/examplesList.js
- examples/helpers/loadFromEnvOrConfig.js
- examples/src/getWithdrawal.js
- examples/src/submitOrder.js
- examples/src/withdraw.js
also: fix amounts when creating withdrawals in other examples to avoid
TOKEN_AMOUNT_TOO_LOW errors
NOTE: this builds on top of #131 so please review that one first
> examples: add cancelWithdrawal

- examples/00.setup.js
`ask` doesn't take a callback any more but returns a promise
> examples/00.setup.js: fix 'ask' path

- src/api/getGasPrice.js
- src/dvf.js
- src/lib/dvf/bindApi.js
- src/lib/stark/createKeyPair.js
- src/lib/stark/createOrderMessage.js
- src/lib/stark/createTransferMessage.js
- src/lib/stark/starkSign.js
same as #125 but rebased
even though this is not a complete implementation it has been in use on the
backend for a long time and since it does not change the default behaviour of
the client I think it's best to have this merged so that backend can follow
the dev branch of the client
> allow injective alternative SW crypto implementation

- src/api/contract/deposit.js
- src/api/contract/depositCancel.js
- src/api/contract/depositReclaim.js
- src/api/contract/fullWithdrawalRequest.js
- src/api/contract/getAllWithdrawalBalances.js
- src/api/contract/getStarkKey.js
- src/api/contract/getWithdrawalBalance.js
- src/api/contract/register.js
- src/api/contract/withdraw.js
- src/api/deposit.js
- src/api/fullWithdrawalRequest.js
- src/api/getWithdrawals.js
- src/api/withdrawOnchain.js
- src/lib/dvf/bindApi.js
in order order to use the v2 api set `dvf.config.starkExUseV2 = true`
> starkEx V2

- .eslintrc.js
- src/api/fastWithdrawalFee.js
- src/lib/dvf/bindApi.js
- src/lib/dvf/createFastWithdrawalPayload.js
- yarn.lock
createFastWithdrawalPayload also allows setting transactionFee manually in
case it is queried earlier by the UI in order to show it to the user
transactionFee set manually should be in base units (as the amount) and is
added to the amount to calculate the actual amount which will be deduced
from users account
> add fastWithdrawalFee and use it in createFastWithdrawalPayload

- package.json
- yarn.lock
https://github.com/LedgerHQ/ledgerjs/releases/tag/v5.34.1
Fixes recent chromium issues
> Update ledger dependencies 

- package.json
- yarn.lock
also:
- examples: add fastWithdrawalFee and fastWithdrawalMaxAmount
- add header authentication for get requests and remove code duplication
- update dvf-utils
> add fastWithdrawalMaxAmount method

- src/lib/stark/createKeyPair.js
fixes issue which manifested when using JS SW implementation
> transfer fixes

- src/api/submitOrder.js
- src/api/transfer.js
submit order validator requires new signature format to be accepted
> Submit order add new signature format

- src/api/eth/send.js
- src/api/registerAndDeposit.js
Bug fix related to : https://app.asana.com/0/1165477653959782/1200042816353811/f
Also part of the fix of : https://app.asana.com/0/1165477653959782/1200042816353814/f
Part of the same PR for practical reasons (testing on the same codebase)
> including chainid on eth.send + register bugfix

- package.json
- yarn.lock
Updating dvf-utils
Indirectly related to :
- https://app.asana.com/0/1165477653959782/1200047524522731/f
- https://app.asana.com/0/1165477653959782/1200001482815220/f
> dep: update dvf-utils dep

- package.json
- src/api/sign/nonceSignature.js
- yarn.lock
Related to https://app.asana.com/0/1165477653959782/1200001482815220/f
> authentication: nonce signing retrocompatible v1

- src/api/sign/sign.js
Related to https://app.asana.com/0/1165477653959782/1200001482815220/f
Authereum to work with human readable message signing
> authereum: Eth human-readable messages signing

- CHANGELOG.md
- examples/29.getRegistrationStatuses.js
- package.json
- src/api/getRegistrationStatuses.js
- src/api/getRegistrationStatuses.test.js
- src/lib/dvf/bindApi.js
- src/lib/dvf/get-authenticated.js
- src/lib/dvf/get-generic.js
Related to : https://app.asana.com/0/1165477653959782/1200108262675781/f
Adds `dvf.getRegistrationStatuses` to check if a given user is registered on DeversiFi and registered on-chain.
> new api method: dvf.getRegistrationStatuses

- README.md
- examples/08.cancelOrder.js
- examples/10.getOrder.js
Related to:
- https://app.asana.com/0/1165477653959782/1200166360332958/f
> Add custom order ID (cid) description

- CHANGELOG.md
- package.json
- src/api/getMinMaxOrderSize.js
- src/api/getMinMaxOrderSize.test.js
- src/lib/dvf/bindApi.js
- Add method for getting min/max order size limits
>#### https://app.asana.com/0/1165477653959782/1200151947525555/f
>#### https://github.com/DeversiFi/dvf-portal/pull/583
> [FEAT] Order min/max size limits

- CHANGELOG.md
- examples/30.publicPermissions.js
- package.json
- src/api/account/permissions.js
- src/api/account/permissions.test.js
- src/api/getPublicPermissions.js
- src/lib/dvf/bindApi.js
Add Public user permission endpints and interactions to the `dvf-client-js` to be used by the UI
> Add public user permissions endpoints

- CHANGELOG.md
- package.json
- src/api/getFeeRate.js
- src/api/getFeeRate.test.js
Related to https://app.asana.com/0/1165477653959782/1200246217213181/f
Adds `symbol` and `feature` arguments to `getFeeRate`
> feat: getFeeRate to accept symbol and feature args

- CHANGELOG.md
- package.json
- src/api/depositV2.js
- src/api/registerAndDeposit.js
Related to https://app.asana.com/0/1165477653959782/1200360977982383/f
> feat: deposit functions to accept opt web3Options

- examples/30.publicPermissions.js
Related to:
- https://app.asana.com/0/1165477653959782/1200321230565720/f
> [FIX] Typo in getPersmissions example

- examples/30.publicPermissions.js
[Typo in 30.publicPermissions.js - setPermisions](https://app.asana.com/0/1165477653959782/1200408511602180)
> Fix typo in Permissions

- CHANGELOG.md
- README.md
- package.json
- src/api/account/tokenBalance.js
- src/api/contract/approve.js
- src/api/contract/isApproved.js
- src/api/deposit.js
- src/api/depositV2.js
- src/api/registerAndDeposit.js
- src/api/test/fixtures/getConf.js
- src/lib/dvf/createFastWithdrawalPayload.js
- src/lib/dvf/token/getTokenAddressFromTokenInfoOrThrow.js
- src/lib/ledger/index.js
- src/lib/stark/ledger/createFastWithdrawalPayload.js
- src/lib/stark/ledger/createSignedOrder.js
- tests/00.complete-path.test.js
Related to https://app.asana.com/0/1165477653959782/1200348965543093/f
> feat: conf change for bridged deposits/withdrawals

- CHANGELOG.md
- package.json
- src/api/contract/approve.js
- src/api/depositV2.js
- src/api/registerAndDeposit.js
- yarn.lock
Related to: https://app.asana.com/0/1165477653959782/1200392066091946/f
> Redesign deposit

- src/lib/dvf/bindApi.js
- src/lib/dvf/createFastWithdrawalPayload.js
- src/lib/dvf/createSignedTransfer.js
- src/lib/dvf/makeCreateSignedTransferTx.js
Related to https://app.asana.com/0/1165477653959782/1200348965543099/f
Will help crafting transfers from low level data
> exposing low-level createSignedTransfer method

- CHANGELOG.md
- package.json
- src/api/transfer.js
- src/lib/dvf/createTransferPayload.js
[Add optional memos to transfers](https://app.asana.com/0/1165477653959782/1200408535084457)
Requires 3 parts:
1. client (this)
2. Backend
3. UI
> Add optional memo to transfer data

- src/api/test/fixtures/getConf.js
- src/lib/dvf/token/getTokenAddressFromTokenInfoOrThrow.js
Related to https://app.asana.com/0/1165477653959782/1200348965543099/f
> conf: native tokens to adopt 0x0... address format

- src/api/ledger/transfer.js
Missed additions from last transfer memo PR for ledger specific transfer functionality
> Add transfer memo to ledger functions

- CHANGELOG.md
- package.json
- src/api/bridgedDeposit.js
- src/api/bridgedDeposit.test.js
- src/api/bridgedWithdraw.js
- src/api/bridgedWithdraw.test.js
- src/api/contract/approve.js
- src/api/contract/depositFromSidechainBridge.js
- src/api/getConfig.test.js
- src/api/getWithdrawals.js
- src/api/registerAndDeposit.js
- src/api/test/fixtures/getConf.js
- src/lib/dvf/bindApi.js
- src/lib/dvf/createTransferPayload.js
- src/lib/dvf/getBridgeContractAddressOrThrow.js
- src/lib/dvf/token/getTokenAddressFromTokenInfoOrThrow.js
- src/lib/util/createPromiseAndCallbackFn.js
Related to https://app.asana.com/0/1165477653959782/1200348965543105/f
> bridges: add bridgedWithdraw and bridgedDeposit

- src/api/cancelOpenOrders.js
- src/api/cancelOpenOrders.test.js
- src/lib/dvf/bindApi.js
Add bulk cancel, supplementary to the following backend PR:
> Add bulk cancellation routing to the dvf bindings

- CHANGELOG.md
- package.json
- src/api/bridgedDeposit.js
- src/api/contract/approve.js
- src/api/contract/isApproved.js
- src/api/eth/call.js
- src/api/eth/getNetwork.js
- src/api/eth/getWeb3ForChain.js
- src/api/eth/send.js
- src/dvf.js
- src/lib/dvf/bindApi.js
Related to https://app.asana.com/0/1165477653959782/1200528790297224/f
> feat: support of multiple web3 providers as params

- CHANGELOG.md
- package.json
- src/api/bridgedDeposit.js
- src/api/bridgedDeposit.test.js
Related to: https://darcs.atlassian.net/browse/VEN-17?atlOrigin=eyJpIjoiMGIxOWM2NThiZDI0NDYwYmI2N2JmNGMyNDg1ZmRmMzciLCJwIjoiaiJ9
> VEN-17 bridge deposit to call validation endpoint

- src/api/submitMarketOrder.js
- src/api/submitOrder.js
- src/lib/dvf/createMarketOrderPayload.js
- src/lib/dvf/createOrderPayload.js
https://darcs.atlassian.net/browse/VEN-114
> VEN-114 - Add platform metadata

- src/api/amm/getAmmFundingOrderData.js
- src/api/amm/getRewardsLockedState.js
- src/api/amm/poolAPY.js
- src/api/amm/poolStoredTokens.js
- src/api/amm/poolSwapFees.js
- src/api/amm/poolTVL.js
- src/api/amm/poolUserAccruedFees.js
- src/api/amm/poolUserLpBalance.js
- src/api/amm/poolUserRewards.js
- src/api/amm/poolVolume24Hours.js
- src/api/amm/postAmmFundingOrders.js
- src/api/amm/postRewardsLockedState.js
- src/lib/dvf/bindApi.js
- src/lib/dvf/get-generic.js
https://darcs.atlassian.net/browse/VEN-198
> VEN-198 - AMM endpoints

- src/lib/dvf/createTransferPayload.js
Adding partner Id to tranfer payload creator
> JUP-130 Add partner Id

- src/api/transfer.js
Add it to underlying functions
> JUP-130: Add partnerId to underlying transfer functions

- src/api/account/select.js
- src/dvf.js
https://darcs.atlassian.net/browse/VEN-221
> VEN-221 - Silent warning in console

- CHANGELOG.md
- package.json
- src/api/register.js
- src/lib/dvf/errorReasons.js
- Return more friendly message when user denies registration TX signature
>#### [[VEN-253] Error message when user deny signature is not suggestive](https://darcs.atlassian.net/browse/VEN-253)
>#### https://github.com/DeversiFi/dvf-portal/pull/1166
> [VEN-253] Error message when user deny signature is not suggestive

- CHANGELOG.md
- package.json
- src/api/amm/poolTvlHistory.js
- src/lib/dvf/bindApi.js
~~https://darcs.atlassian.net/browse/VEN-198~~
https://darcs.atlassian.net/browse/VEN-327
> VEN-327 - Add poolTvlHistory endpoint

- examples/27.ammDeposit.js
- examples/28.ammWithdrawal.js
Related to https://darcs.atlassian.net/browse/JUP-34
Allows to test AMM examples and observe behavior. Should pivot to generated examples later
> Jup 34/amm deposit and withraw example

- src/api/amm/poolTokensRate.js
- src/lib/dvf/bindApi.js
https://darcs.atlassian.net/browse/VEN-345
> VEN-345 - Add poolTokensRate endpoint

- package.json
- yarn.lock
Uses latest hash from https://github.com/DeversiFi/dvf-utils/pull/46
> JUP-181: Bump dvf-utils hash

- package.json
- yarn.lock
Only for solving dep conflict with dvf-stark-trading https://github.com/DeversiFi/launch-deversifi/pull/2068
> dep: update dvf-utils

- src/api/getWithdrawals.js
Related to https://darcs.slack.com/archives/GL7JLS5RD/p1638380099333800
> fix: Excluding LP- tokens from balance withdrawals

- src/api/contract/getAllWithdrawalBalancesEthAddress.js
- src/api/contract/getWithdrawalBalanceEthAddress.js
- src/api/getWithdrawals.js
- src/lib/dvf/bindApi.js
Additional logic missed from original PR to fetch the pending withdrawal balances of a user
> JUP-168 withdrawal balance eth key

- src/lib/stark/ledger/createSignedTransfer.js
Related to https://darcs.atlassian.net/browse/JUP-276
> fix: JUP-276 pad transfer recpient eth addr ledger

- package.json
- src/lib/ledger/provideContractData.js
- src/lib/ledger/provideTokenSignature.js
- yarn.lock
Matching versions of dvf-portal so we don't get duplicated packages
Note: please maintain the same version of ledger libs as they are around ~700kb+ gzipped
> Library updates to minimize integration size

- src/api/bitfinex/transfers.js
- src/lib/dvf/bindApi.js
https://darcs.atlassian.net/browse/VEN-438
> VEN-438 - Bitfinex support page

- CHANGELOG.md
- package.json
- src/dvf.js
Related to https://darcs.atlassian.net/browse/VEN-502
> bug: VEN-502 DEFAULT web3 provider if unspecified

- src/api/account/getReferralId.js
- src/api/account/getReferralRewards.js
- src/api/account/getRemainingSpins.js
- src/api/account/postReferralSpin.js
- src/api/bridgedDeposit.js
- src/api/depositV2.js
- src/lib/dvf/bindApi.js
https://darcs.atlassian.net/browse/UAS-9
> UAS-9 - Add referral endpoints

- package.json
- yarn.lock
use joi instead of @hapi/joi 
https://github.com/DeversiFi/dvf-utils/pull/55
> [chore] update dvf-utils to 1.0.4

- CHANGELOG.md
- package.json
- src/api/transferAndWithdraw.js
- src/dvf.js
- src/lib/dvf/bindApi.js
- src/lib/dvf/createTransferAndWithdrawPayload.js
- src/lib/dvf/makeCreateSignedTransferTx.js
- src/lib/dvf/token/getSafeQuantizedAmountOrThrow.js
- src/lib/keystore/index.js
- src/lib/ledger/index.js
- src/lib/ledger/makeCreateSignedTransferTxLedger.js
- src/lib/stark/ledger/createSignedTransfer.js
- yarn.lock
Breaking change in some internal functions (create transfer and withdraw payload)
> [YIELD-113] Transfer with fee

- package.json
- yarn.lock
Update utils for the updated copy
@Matko95 portal should also update `dvf-client-js` reference once this is merged
> Update utils to v1.2.0

- examples/28.ammWithdrawal.js
> [JUP]: Fix amm withdrawal example

- package.json
- src/lib/dvf/createTransferAndWithdrawPayload.js
- yarn.lock
Updating dvf-utils reference, must be merged and tagged first
https://github.com/rhinofi/dvf-utils/pull/67
> [MARKETS-258]: Withdrawal fee round down

- package.json
- src/api/amm/poolsData.js
- src/api/amm/poolsUserData.js
- src/lib/dvf/bindApi.js
- src/lib/dvf/get-generic.js
- yarn.lock
- Add new endpoints for AMM pools
- Update `get-generic` to use `request` from `dvf-utils` to allow to pass several values for one query param
https://darcs.atlassian.net/browse/VEN-547
> VEN-547 - new pools endpoints

- src/api/topPerformersTokens.js
- src/lib/dvf/bindApi.js
https://darcs.atlassian.net/browse/UDS-284
> UDS-284 - Add top performers tokens endpoint

- nix/pkgs-private.nix
- package.json
Cherry picking from Adrian's PR since unsure if the rest should be merged or not
> [devops] fix deploy step

- package.json
- src/api/bridgedWithdraw.js
* Back end part already done: https://github.com/rhinofi/rhino-core/pull/3971
* Front end part in progress, waiting for this so I can bump the client-js version
> [CHAIN-630] Remove bridge withdraw isFeeUsd

- package.json
- src/api/contract/abi/BridgeDepositContract.abi.json
Simply update the contract ABI in the client-js. Contract is backwards compatible hence only new functions are added. Stark-trading uses the contract from this package
> [BRIDGES-1225]: Update the bridge contract ABI
