- src/api/contract/getStarkKey.js
- src/api/contract/getWithdrawalBalance.js
- src/api/getWithdrawals.js
- src/api/getWithdrawals.test.js
- src/lib/dvf/bindApi.js
This updates getWithdrawals to return withdrawal requests which are ready as well as the ones which are not ready.
The withdrawal requests which are ready will show a total amount available for withdrawal clubbed together by token.
The withdrawal requests which are not ready will show individual withdrawal requests which have been made by the user(eg. ETH 1, ETH 5, ETH 9)
> Withdrawals to return ready as well as pending withdrawals

- package.json
- src/api/getVaultId.js
- src/api/getVaultIdFromServer.js
- src/api/submitOrderNew.js
- src/config.js
- src/dvf.js
- src/lib/dvf/bindApi.js
- src/lib/dvf/createOrderMetaData.js
- src/lib/dvf/createOrderPayload.js
- src/lib/stark/createKeyPair.js
- src/lib/stark/createOrder.js
- src/lib/stark/createOrderMessage.js
- src/lib/stark/createOrderMetaData.js
- src/lib/stark/ledger/createOrderMetaData.js
- src/lib/validators/validateProps.js
- yarn.lock
this PR contains:
- changes which are meant to facilitate testing of stark-trading
- proposed improvement to implementation and interface of submitOrder
- getVaultId api method which is used to retrieve vault id for user/token
on demand, instead of relying on spareStarkVaultId
> test helpers, submitOrderNew, improved createOrderMetaData, getVaultId

- src/api/deposit.js
Using `getVaultId()` Pub API call to retrieve new vault id for depositing a new token and assigning a new stark vault id.
There is no need to call getUserConfig at the end of deposit as a new Vault Id is already updated in dvf.config by `getVaultId()`.
> getVaultId for new token deposit

- package.json
- src/api/getConfig.test.js
- src/api/getUserConfig.test.js
- src/api/test/fixtures/getConf.js
- src/lib/dvf/computeBuySellDats.js
- src/lib/dvf/token/BN.js
- src/lib/dvf/token/getTokenInfo.js
- src/lib/dvf/token/splitSymbol.js
- src/lib/stark/createOrder.js
Order sell and buy amounts need to be calculated and rounded the same way as currently done on the backend to ensure amounts match and orders are verified correctly.
- Extracted buy and sell amount calculation out of create order method.
- Used the same calculation logic and code as the backend to compute buy and sell amounts.
> Order Price and Amount Precision

- src/dvf.js
- src/lib/stark/ledger/createSignedOrder.js
- src/lib/stark/ledger/createSignedTransfer.js
- ERC20 Token Info needs a different logic for testnet tokens as compared to mainnet tokens. This is being handled in this fix by using chainId from web3.
> handle tokeninfo additio for ledger based on eth network

- src/api/register.js
- src/api/register.test.js
Adding nonce and signature as optional parameters to register method to improve user journey for Metamask and Ledger wallet users by avoiding multiple requests to sign for authentication.
> adding nonce and signature to register method

- package.json
- src/api/getConfig.test.js
- src/api/getUserConfig.test.js
- src/api/test/fixtures/getConf.js
- src/lib/stark/createMarketOrder.js
- src/lib/stark/createOrder.js
- yarn.lock
Incorporate settle spread for stable tokens like USDT and BTC
- Latest settle spread is retrieved from user config
- This is sent to dvf-utils/computeBuySellData for amount calculations
**Note: This change is dependent on requires https://github.com/DeversiFi/launch-deversifi/pull/588**
> Incorporate Settle Spread

- src/api/ledger/deposit.js
- src/api/ledger/deposit.test.js
Fix for ledger deposit transactions failing when too many decimal places are used.
Using common validation used in other methods to validate and update precision to avoid errors.
> Bugfix for ledger transaction failure

- package.json
- src/api/deposit.js
- src/api/deposit.test.js
- src/config.js
- src/lib/dvf/bindApi.js
- src/lib/dvf/token/maxQuantizedDecimalPlaces.js
- yarn.lock
Use the max decimal place precision possible based on a quantized unit and default decimal precision supported by BitFinex.
> Use Decimal Precision Based on Quantized Unit

- package.json
- src/dvf.js
- src/lib/dvf/token/getTokenInfo.js
- yarn.lock
- Using dvf utils method to convert between Deversifi and Bitfinex token names.
- This enables adding mapping between USDC and UDC plus others when required
Note: This PR is dependant on https://github.com/DeversiFi/dvf-utils/pull/4
yarn lock needs to be regenerated after dvf utils is merged
> Mapping between Bitfinex and Deversifi tokens

- examples/node_sell_eth_infura.js
a tested working version for instancing infura requests example in README.md.
however i don't recommend using this fix because it could look pretty confusing
giving the fact that all of the examples in ./examples are using envVars and not this syntax.
my suggestion is to modify this part:
___
const privateKey = '8F085...' // Account's private key
const infuraKey = '9e28b...' // Your Infura API KEY
const infuraURL = 'https://mainnet.infura.io/v3/' + infuraKey
___
and change it to the example in 05.submitOrder and link to this file, insted of node_sell_eth_infura.js
> 📃 missing file from a link in README.md

- examples/00.setup.js
- examples/01.register.js
- examples/02.deposit.js
- examples/03.getDeposits.js
- examples/04.getBalance.js
- examples/05.submitOrder.js
- examples/06.getOrders.js
- examples/07.getOrders_forSymbolPair.js
- examples/08.cancelOrder.js
- examples/09.getConfig.js
- examples/10.getOrder.js
- examples/11.getOrdersHist.js
- examples/12.getUserConfig.js
- examples/13.withdraw.js
- examples/14.getWithdrawals.js
- examples/15.getWithdrawal.js
- examples/16.withdrawOnChain.js
- examples/17.fullWithdrawalRequest.js
- examples/18.getVaultId.js
- examples/19.ledgerDeposit.js
- examples/20.ledgerSubmitOrder.js
- examples/21.ledgerWithdraw.js
- examples/helpers/buildExamples.js
- examples/helpers/example.js.tmpl
- examples/helpers/loadFromEnvOrConfig.js
- examples/src/submitOrder.js
this supersedes #109 as Meers last comment on that PR has not been addressed
also:
- update examples/src/submitOrder (as the example was edited directly not
following what's described in https://github.com/DeversiFi/dvf-client-js/pull/109#issuecomment-674391263)
- make examples/helpers/buildExamples.js executable so that it can be run
directly
> examples: allow setting api url via env var / config.json

- src/api/contract/register.js
Using starkware v2 we can specify which ethAddress we are registering and when we want to register a contract wallet that's not the address that will be on dvf, so we need to specify it
> feat: contract wallet address as an argument on register

- src/api/deposit.js
- src/api/submitMarketOrder.js
- src/api/submitOrder.js
- src/lib/dvf/createMarketOrderPayload.js
- src/lib/dvf/createOrderPayload.js
- src/lib/stark/createOrder.js
- src/lib/stark/ledger/createDepositData.js
Nonce and signature are passed to getVaultId as a temporary solution for unnecessary nonce signing
> Pass nonce and signature to deposit / order submission to avoid unnecessary signing

- src/api/depositV2.js
- src/api/eth/send.js
Related to https://app.asana.com/0/1165477653959782/1199968011428762/f
`transactionHashCb` callback to behave like a standard callback and have error as first argument (making the wrapper promise reject in case of error rather than never resolve)
> depositV2: transactioHashCallback to propagate err

- src/api/submitOrder.test.js
- src/lib/stark/createOrder.js
Related to https://app.asana.com/0/1165477653959782/1199973419266868/f
In `dvf-client-js` > `createOrder` function amount was rounded using a price rounding function instead of amount rounding function.
Switching to amount rounding function.
**/!\** Note that I couldn't measure the impact of this, as from the portal the amounts are rounded the same way regardless of this change (maybe because of some priori UI-side rounding).
> fix: prepareAmountBN in createOrder for amount

- src/api/sign/nonceSignature.js
- src/api/sign/sign.js
Related to https://app.asana.com/0/1165477653959782/1200001482815220/f
Signs nonce like before until `authVersion` is added to server `getConf` response and will start signing message instead
> authentication: nonce replaced by message signing

- src/api/getBalance.js
- src/api/getBalance.test.js
Related to : https://app.asana.com/0/1165477653959782/1199992925843663/f
`getBalance` endpoint accepting `params` instead of just `token` (adding extra `fields` optional param)
> getBalance to accept arbitrary params as payload

- examples/05.submitOrder.js
- examples/08.cancelOrder.js
- examples/10.getOrder.js
- src/api/cancelOrder.js
- src/api/cancelOrder.test.js
- src/api/getOrder.js
- src/api/getOrder.test.js
- src/lib/util/extractOrderIdsInput.js
- src/lib/validators/cid.js
- src/lib/validators/validateAssertions.js
Related to : https://app.asana.com/0/1165477653959782/1200105839681745/f
Retrocompatible addition to enable `{cid: 'yyy'}`, {orderId: 'xxx'}` or `'xxx'` to be passed as input for `getOrder` and `cancelOrder`
> orders: allow to use orderId or cid for get/cancel

- CHANGELOG.md
- package.json
- src/lib/dvf/bindApi.js
- src/lib/dvf/get-authenticated.js
Related to https://app.asana.com/0/1165477653959782/1200151347471493/f
- Exposing `dvf.getAuthenticated` for arbitrary calls to GET endpoints
- Allowing custom headers in `dvf.getAuthenticated`
> exposing getAuthenticated + custom headers

- CHANGELOG.md
- src/api/register.js
- src/api/registerAndDeposit.js
Related to : https://app.asana.com/0/1165477653959782/1200178777069035/f
- Adding optional `meta` field in `dvf.register` and `dvf.registerAndDeposit`
> feat: optional meta field for register endpoint

- src/api/depositV2.js
[Unexpected error when making deposits](https://app.asana.com/0/1165477653959782/1200425422177502)
**Issue**
Validations on `deposits` endpoint cannot revert an L1 transaction in flight, hence it'll only cause bad UX as users will see failure message for deposit however it will go through anyways
**Solution**
Transform into 2 part deposit by calling a validation endpoint to ensure upcoming deposit will be valid. This does not guarantee that all deposits will be correctly validated however we are not capable of validating if L1 transactions are submitted directly before calling this endpoint
Requires 3 part fix:
- Client (this)
- UI
> call validate endpoint inside v2 deposit function

- src/api/depositV2.js
Use auth header authentication for all of depositv2 requests
@benudall would you be able to pull this branch and test the example again? I'm unable to get any results from examples they seem to be hanging forever
> Use auth header authentication for DepositV2

- CHANGELOG.md
- package.json
- src/lib/dvf/createMarketOrderPayload.js
- src/lib/dvf/createOrderPayload.js
- Update feeRate check on order payload creation to replace feeRate only if not present and preserve falsy values like 0 to allow staking
>#### [[VEN-140] Governance: Incorrect behaviour when user try to unstake max value on Deversifi](https://darcs.atlassian.net/browse/VEN-140)
>#### https://github.com/DeversiFi/launch-deversifi/pull/1743
>#### https://github.com/DeversiFi/dvf-portal/pull/974
> [VEN-140] Governance: Incorrect behaviour when user try to unstake max value on Deversifi

- src/api/walletFailedEvent.js
- src/api/walletSuccessEvent.js
- src/lib/dvf/bindApi.js
- src/lib/dvf/post-authenticated.js
- src/lib/dvf/post-generic.js
https://darcs.atlassian.net/browse/VEN-322
* Move `walletFailedEvent` and `walletSuccessEvent` endpoints to `dvf-client-js`
* Refactor `post` code and use it in the endpoints above
> VEN-322 - Move wallet events to dvf-client-js

- CHANGELOG.md
- examples/27.ammDeposit.js
- examples/28.ammWithdrawal.js
- examples/src/ammDeposit.js
- examples/src/ammWithdrawal.js
- package.json
- src/api/amm/applyFundingOrderDataSlippage.js
- src/api/amm/getAmmFundingOrderData.js
- src/api/amm/postAmmFundingOrders.js
- src/api/amm/schemas.js
- src/lib/dvf/bindApi.js
- yarn.lock
Apply the slippage to the funding order's data before signing
- Fetch funding order data from backend
- Reduce `amountBuy` for each order
- Sign the result
Must be used in UI before submitting the order, it does not calculate the non stark values, they can be handled separately
NOTE: a large chunk of changes in example files was due to inconsistency between template and generated versions of deposit and withdrawal examples
> [JUP-352]: Add fundingOrder slippage calculation to stark orders

- examples/16.getWithdrawal.js
- examples/27.ammDeposit.js
- examples/28.ammWithdrawal.js
- examples/helpers/example.js.tmpl
Some examples require starkKey but the default example generator does not include it. Additionally the old `withdraw` requires onchain registration which we do not perform anymore
> [JUP]: Resolve out of date examples

- src/api/depositV2.js
- src/api/test/helpers/instance.js
Do not proceed with L1 tx if starkKey or vaultId does not match backend response
can also directly use `vaultId` and `starkKey` from the result of `deposit-validation`
> [VEN-581]: Use deposit validation result to ensure the transaction detail are correct

- .github/workflows/test-and-publish.yaml
- nix/netrc-create.sh
same as: https://github.com/rhinofi/dvf-utils/pull/189
also:
- update gh action step versions
- fix piping into .github/netrc-create.sh
> [devops] load github token via GCP secret manager

- package.json
- src/api/storeStarkL1Registration.js
This could cause race conditions in the UI as `getUserConf` is mutating the config
> [PI-139]: Do not mutate the object config during l1 storage

- src/api/contract/getAllWithdrawalBalances.js
- src/api/contract/getAllWithdrawalBalancesEthAddress.js
- src/api/contract/getWithdrawalBalance.js
- src/api/contract/getWithdrawalBalanceEthAddress.js
In order to allow the Portal to migrate to Vite, we had to patch code in the @rhino.fi/client-js package. This is not ideal and we should really update client-js to fix these problems. This PR is to complete part of that work.
The following files need updating in @rhino.fi/client-js to allow these patches to be removed.
1. @rhino.fi/client-js/src/api/contract/getAllWithdrawalBalances.js 
2. @rhino.fi/client-js/src/api/contract/getAllWithdrawalBalancesEthAddress.js
3. @rhino.fi/client-js/src/api/contract/getWithdrawalBalance.js
4. @rhino.fi/client-js/src/api/contract/getWithdrawalBalanceEthAddress.js
All of the files above need the following code change to replace
`return (withdrawalBalance = await dvf.eth.call(`
with 
`return (await dvf.eth.call(`
> feat - remove undeclared vars

- package.json
- src/lib/ledger/selectTransport.js
In order to allow the portal to migrate to Vite, we had to patch code in the @rhino.fi/client-js package. This is not ideal and we should really update client-js to fix these problems. This PR is to complete part of that work.
The following file has been updated in @rhino.fi/client-js to allow these patches to be removed.
@rhino.fi/client-js/src/lib/ledger/selectTransport.js
> feature - PI-390 - remove reference to ledger node-hid package
